language: julia
julia:
  - nightly
  - 1.1
  - 1.0
notifications:
  email: false
script:
  - julia -e 'using Pkg; Pkg.instantiate(); if VERSION >= v"1.1" Pkg.build(; verbose = true) else Pkg.build() end; Pkg.test(coverage=true)' 
after_success:
  - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia -e 'using Pkg; import WignerD; cd(joinpath(dirname(pathof(WignerD)))); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi)),"..")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi